title: ReApptor TypeScript PagedList
tagline: TODO Description.
description: TODO Description.
author: ReApptor
social:
  name: ReApptor
  links:
    - https://www.linkedin.com/company/reapptor/
image: https://raw.githubusercontent.com/ReApptor/ReApptor.TypeScript.PagedList/main/ReApptor.png
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-relative-links
webmaster_verifications:
  google: nxCkklgQ7aYkXjK86Y4jcCrSWpNnBKLjz2jKxc3m46o
relative_links:
  enabled: true
